web/router.ex
defmodule Ginga.Router do
  use Ginga.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end


  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything
  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  # This pipeline is created for use within the admin namespace.
  # It looks for a valid token in the session - but in the 'admin' location of guardian
  # This keeps the session credentials seperate for the main site, and the admin site
  # It's very possible that a user is logged into the main site but not the admin
  # or it could be that you're logged into both.
  # This does not conflict with the browser_auth pipeline.
  # If it doesn't find a JWT in the location it doesn't do anything
  pipeline :admin_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
    plug Guardian.Plug.LoadResource, key: :admin
  end

  # We need this pipeline to load the token when we're impersonating.
  # We don't want to load the resource though, just verify the token
  pipeline :impersonation_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
  end




  scope "/", Ginga do
    # We pipe this through the browser_auth to fetch logged in people
    # We pipe this through the impersonation_browser_auth to know if we're impersonating
    # We don't just pipe it through admin_browser_auth because that also loads the resource
    pipe_through [:browser, :browser_auth, :impersonation_browser_auth]

    get "/", PageController, :index
    delete "/logout", AuthController, :logout

    get "/signup/:plan",  UserController, :new

    resources "/authorizations", AuthorizationController
    resources "/tokens", TokenController

    get "/private", PrivatePageController, :index

    get "/pricing/", PageController, :pricing
    get "/guide/", PageController, :guide
    get "/chat/messages",RethinkdbController, :messages
    post "/rethinkdb",PageController, :rethinkdb
    get "/ts", PageController, :react_test


	  get "/app/", PageController, :app
	  get "/ejabberd", EjabberdController, :index
	  resources "/posts", PostController
	  get "/chat2", PageController,:chat
  	get "/app/", PageController, :app
  	get "/ejabberd", EjabberdController, :index
  	resources "/posts", PostController
    get "/settings", PageController,:settings
    get "/ts", PageController, :react_test
    get "/messages", PageController,:messages

    get "/xmpp",  EjabberdWsController ,:upgrade
    post "/xmpp",  EjabberdWsController,:upgrade
    get "/account/email/verify/:token", UserController,:verify_email


     get "/logout", AuthController, :logout

     get "/boards",PageController, :app
     get "/chat",PageController, :app
     get "/tasks",PageController, :app
     get "/chat/threads/:id",PageController, :app
     get "/chat/channels/:id",PageController, :app



  end

  # This scope is the main authentication area for Ueberauth
  scope "/auth", Ginga do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/:identity", AuthController, :login
    get "/:identity/callback", AuthController, :callback
    post "/:identity/callback", AuthController, :callback

  end

  # This scope is intended for admin users.
  # Normal users can only go to the login page
  scope "/admin", Ginga.Admin, as: :admin do
    pipe_through [:browser, :admin_browser_auth] # Use the default browser stack

    get "/login", SessionController, :new, as: :login
    get "/login/:identity", SessionController, :new
    post "/auth/:identity/callback", SessionController, :callback
    get "/logout", SessionController, :logout
    delete "/logout", SessionController, :logout, as: :logout
    post "/impersonate/:user_id", SessionController, :impersonate, as: :impersonation
    delete "/impersonate", SessionController, :stop_impersonating

    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  scope "/api", Ginga do
    pipe_through [:api]
    scope "/v1" do
      post "/sessions", SessionController, :create
      delete "/sessions", SessionController, :delete
      get "/current_user", CurrentUserController, :show
      get "/rooms", XMPPController, :rooms
      resources "boards", BoardController, only: [:index, :create] do
        resources "cards", CardController, only: [:show]

      end
       get "/commands/:term", CommandController,:suggestions
        resources "/teams", TeamController, except: []
        resources "/analytics", AnalyticController, except: []
        resources "/push_notifications", PushNotificationController, except: []
        resources "/files", FileController, except: []

      resources "/events", Ginga.EventsController, except: []
  	  resources "/streams", Ginga.StreamsController, except: []
  	  resources "/streamdefs", Ginga.StreamDefsController, except: []
  	  post "/authorize", Ginga.OauthController, :authorize_post
  	  get "/authorize", Ginga.OauthController, :authorize_get

  	  resources "/accounts", AccountController, except: [:new, :edit]
     resources "/tasks", TaskController, except: [:new, :edit]
      resources "/opportunities", OpportunityController, except: [:new, :edit]
      resources "/comments", CommentController, except: [:new, :edit]
      resources "/campaigns", CampaignController, except: [:new, :edit]
      resources "/contacts", ContactController, except: [:new, :edit]
      resources "/companies", CompanyController, except: [:new, :edit]
      resources "/webhooks", WebhookController, except: []


    end
  end


  pipeline :auth do
      plug :put_oauth_strategy
    end



  scope "/oauth_legacy", alias: Ginga do
      pipe_through [:browser]
      get "/", OauthController, :index
      get "/callback", OauthController, :callback
      post "/resource", OauthController, :get_access_token

    end




      # `@current_user`.
      defp assign_current_user(conn, _) do
        assign(conn, :current_user, get_session(conn, :current_user))
      end

      # Fetch the configured strategy from the router's config and store the
      # initialized strategy into `conn.private.oauth2_strategy`.
      defp put_oauth_strategy(conn, _) do
        {strategy, opts} = Ginga.Endpoint.config(:oauth2)
        put_private(conn, :oauth2_strategy, apply(strategy, :new, [opts]))
      end
end

web/views/admin/layout_view.ex
defmodule Ginga.Admin.LayoutView do
  use Ginga.Web, :view
end

web/views/layout_view.ex
defmodule Ginga.LayoutView do
  use Ginga.Web, :view
  import Plug.Conn
  require Logger




  def logged_in(conn) do
    case  current_user(conn) do
      nil -> false
      _  -> true
    end

  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="description" content="Plug lets you do business better. Seamless team communication and project management.">
    <meta name="author" content="Sparkplug">

    <title>Plug: Do Business Better with Seamless team communication, simplified project management and efficient customer support.</title>

    <!--Import materialize.css-->
     <link type="text/css" rel="stylesheet" href="/css/plug.css"  media="screen,projection"/>
     <link type="text/css" rel="stylesheet" href="/css/platformicons/platformicons.css"  media="screen,projection"/>



    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>


    <!--[if lt IE 9]>
    <script src='https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'></script>
    <script src='https://oss.maxcdn.com/respond/1.4.2/respond.min.js'></script>
    <![endif]-->
    <script src="/plugins/modernizr/modernizr.min.js"></script>

    <!-- Script tags for landing page -->
    <script src="/js/plug/lib.min.js"></script>
    <script src="/js/plug/global.min.js"></script>
    <script src="/js/plug/waypoints.min.js"></script>
    <script src="/js/plug/moment.min.js"></script>
    <script src="/js/plug/home.js"></script>

  </head>

  <body >
    <header class="home">
      <div class="container">
        <a href="/" class='logo'><img src="/images/logo.png"> </a>

        <ul class="user-nav">
          <li class="hidden-xs"><a href="/pricing/" class="pricing-link">Pricing</a></li>
          <li class="hidden-xs"><a href="/guide/" class="pricing-link">Guide</a></li>
          <li class="hidden-xs"><a href="/" class="pricing-link">Blog</a></li>
          <%= if @current_user do %>
           <li><a href="/logout">Logout</a></li>

          <% else %>
          <li><a href="/app/">Sign in</a></li>
          <li class="divider"></li>
          <li><%= link "Start for free", to: page_path(@conn, :pricing), class: "cta" %></li>
          <% end %>
        </ul>
      </div>
    </header>
    <%= if  get_flash(@conn, :info) do %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
       <%= if  get_flash(@conn, :error) do %>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

    <%= render @view_module, @view_template, assigns %>



<footer id="footer">
    <div class="container">

        <div class="row">
            <div class="col-sm-3 pull-right">
                <ul class="services list-unstyled">
                    <li class="twitter align-right"><a href="http://twitter.com/sparkplugea">Twitter</a></li>
                    <li class="github align-right"><a href="https://facebook.com/sparkplug">Facebook</a></li>

                </ul>
                <p class="copyright align-right"><small>&copy; 2016 sparkpl.ug</small></p>
            </div>
            <div class="col-sm-5">
                <ul class="list-unstyled">
                    <li><a href="/guide/">Terms</a></li>

                </ul>
            </div>
            <div class="col-sm-5">
                <ul class="list-unstyled">
                    <li><a href="/about/">About Us</a></li>

                </ul>
            </div>

        </div>
    </div>
</footer>


  </body>
</html>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="description" content="Plug lets you do business better. Seamless team communication and project management.">
    <meta name="author" content="Sparkplug">

    <title>Plug: Do Business Better with Seamless team communication, simplified project management and efficient customer support.</title>

    <!--Import materialize.css-->
     <link type="text/css" rel="stylesheet" href="/css/plug.css"  media="screen,projection"/>
     <link type="text/css" rel="stylesheet" href="/css/platformicons/platformicons.css"  media="screen,projection"/>



    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>


    <!--[if lt IE 9]>
    <script src='https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'></script>
    <script src='https://oss.maxcdn.com/respond/1.4.2/respond.min.js'></script>
    <![endif]-->
    <script src="/plugins/modernizr/modernizr.min.js"></script>

    <!-- Script tags for landing page -->
    <script src="/js/plug/lib.min.js"></script>
    <script src="/js/plug/global.min.js"></script>
    <script src="/js/plug/waypoints.min.js"></script>
    <script src="/js/plug/moment.min.js"></script>
    <script src="/js/plug/home.js"></script>

  </head>

  <body >
    <header class="home">
      <div class="container">
        <a href="/" class='logo'>Plug</a>

        <ul class="user-nav">
          <li class="hidden-xs"><a href="/pricing/" class="pricing-link">Pricing</a></li>
          <li class="hidden-xs"><a href="/guide/" class="pricing-link">Guide</a></li>
          <li class="hidden-xs"><a href="/" class="pricing-link">Blog</a></li>
          <%= if @user do %>
          <li><a href="/logout/">Logout</a></li>

          <% else %>
          <li><a href="/login/">Sign in</a></li>
          <li class="divider"></li>
          <li><a href="/signup/" class="cta">Start for free</a></li>
          <% end %>


        </ul>
      </div>
    </header>

    <%= render @view_module, @view_template, assigns %>



<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <h4>Quick Links</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3 pull-right">
                <ul class="services list-unstyled">
                    <li class="twitter align-right"><a href="http://twitter.com/getsentry">Twitter</a></li>
                    <li class="github align-right"><a href="https://github.com/getsentry/sentry">GitHub</a></li>
                    <li class="dribbble align-right"><a href="http://dribbble.com/ckj/projects/80366-Sentry">Dribbble</a></li>
                </ul>
                <p class="copyright align-right"><small>&copy; 2015 GetSentry.com</small></p>
            </div>
            <div class="col-sm-3">
                <ul class="list-unstyled">
                    <li><a href="/pricing/">Plans and Pricing</a></li>
                    <li><a href="/">Blog</a></li>
                    <li><a href="/guide/">Docs</a></li>

                </ul>
            </div>
            <div class="col-sm-3">
                <ul class="list-unstyled">
                    <li><a href="/about/">About Us</a></li>
                    <li><a href="/privacy/">Privacy Policy</a></li>
                    <li><a href="/security/">Security</a></li>
                    <li><a href="/terms/">Terms of Service</a></li>
                    <li><a href="/thanks/">Thank Yous</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <ul class="list-unstyled">
                    <li><a href="https://www.getsentry.com/for/javascript/" title="JavaScript Error Tracking">JavaScript</a></li>
                    <li><a href="https://www.getsentry.com/for/ruby/" title="Ruby Error Tracking">Ruby</a></li>
                    <li><a href="https://www.getsentry.com/for/python/" title="Python Error Tracking">Python</a></li>
                    <li><a href="https://www.getsentry.com/for/php/" title="PHP Error Tracking">PHP</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>


  </body>
</html>

web/templates/layout/chat.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="Learn how to quickly get started using our CSS framework. We have guides for a variety of skill levels.">
    <title>Getting Started - Materialize</title>
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="images/favicon/apple-touch-icon-152x152.png">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
    <link rel="icon" href="images/favicon/favicon-32x32.png" sizes="32x32">
    <!--  Android 5 Chrome Color-->
    <meta name="theme-color" content="#EE6E73">
    <!-- CSS-->

    <link href="/css/src-materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="/css/elements.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="http://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet" type="text/css">
    <script>
      window.liveSettings = {
        api_key: "a0b49b34b93844c38eaee15690d86413",
        picker: "bottom-right",
        detectlang: true,
        dynamic: true,
        autocollect: true
      };
    </script>
    <script src="//cdn.transifex.com/live.js"></script>
  </head>
  <body>



    <main>
      <nav class="top-nav">
        <div class="container">
          <div class="nav-wrapper"><a class="page-title">Page Title</a></div>
        </div>
      </nav>

        <div class="row">
           <!-- <div class="container"> -->
          <div class="col s3">
            <header>
            <div class="container">
              <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full"><i class="mdi-navigation-menu"></i></a></div>
      <ul id="nav-mobile" class="side-nav fixed">
        <li class="logo"><a id="logo-container" href="/" class="brand-logo"></a></li>
        <li class="bold"><h6 class="waves-effect waves-teal">Organization</h6></li>

        <li class="no-padding">
          <ul class="collapsible collapsible-accordion">
            <li class="bold"><a class="collapsible-header active waves-effect waves-teal">Chat</a>
              <div class="collapsible-body">
                <ul>
                  <li><a href="/chat/">Activity</a></li>
                  <li><a href="/messages/">Messages</a></li>
                  <li><a href="/messages/">Channels</a></li>
                  <li><a href="/people">People</a></li>
                  <li><a href="/teams">Teams</a></li>
                </ul>
              </div>
            </li>
            <li class="bold"><a class="collapsible-header  waves-effect waves-teal">Settings</a>
              <div class="collapsible-body">
                <ul>
                  <li><a href="badges.html">Organization</a></li>
                  <li><a href="buttons.html">Manage Plan</a></li>
                  <li><a href="cards.html">Billing Information</a></li>
                  <li><a href="collections.html">Payment History</a></li>
                </ul>
              </div>
            </li>
          </ul>
        </li>
        <li class="bold"><a href="getting-started.html" class="waves-effect waves-teal">Getting Started</a></li>
        <li class="bold"><a href="getting-started.html" class="waves-effect waves-teal">Contact Support</a></li>
      </ul>
    </header>
  </div>
          <div class="col s12">
            <%= render @view_module, @view_template, assigns %>
          </div>

        <!-- </div> -->
    <!-- </div> -->

    </main>
    <footer class="page-footer">
      <div class="container">
        <div class="row">

          <div class="col l12 s12">
            <h5 class="white-text">Join the Discussion</h5>
            <p class="grey-text text-lighten-4">We have a Plug chat room set up where you can talk directly with us. Come in and discuss new features, future goals, general problems or questions, or anything else you can think of.</p>
            <a class="btn waves-effect waves-light red lighten-3" target="_blank" href="">Chat</a>
          </div>

        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2015 Plug.
        <a class="grey-text text-lighten-4 center" href="http://sparkpl.ug">Made with ♥ in Uganda</a>
        </div>
      </div>
    </footer>
    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script>if (!window.jQuery) { document.write('<script src="bin/jquery-2.1.1.min.js"><\/script>'); }
    </script>
    <script src="/js/jquery.timeago.min.js"></script>
    <script src="js/prism.js"></script>
    <script src="/js/materialize.js"></script>
    <script src="js/init.js"></script>
    <!-- Twitter Button -->
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

    <!-- Google Plus Button-->
    <script src="https://apis.google.com/js/platform.js" async defer></script>

    <!--  Google Analytics  -->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-xxxxxxxx-x', 'auto');
    ga('require', 'displayfeatures');
    ga('send', 'pageview');
    </script>
  </body>
</html>

web/templates/layout/chatapp.html.eex
<!DOCTYPE html>
<html>
<head>
    <title>Soko :: Spark Your Business</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body >
<section id="container">
    <%= render @view_module, @view_template, assigns %>
</section>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="/js/bundle.js"></script>
</body>
</html>

web/templates/layout/impersonation.html.eex
<%= if admin_logged_in?(@conn) && logged_in?(@conn) do %>
  <div class='impersonation-bar'>
    <%= link "Stop impersonating #{current_user(@conn).name}",
             to: admin_session_path(@conn, :stop_impersonating),
             method: "DELETE",
             class: "btn btn-xs btn-warning"
    %>
  </div>
<% end %>

web/templates/layout/login.html.eex
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><%= @title %></title>
        <meta name="description" content="" />
        <link rel="icon" type="image/png" href="./media/favicon.ico" />
		   <link rel="stylesheet" href="/css/login.css?124">

	       <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700'>


        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0" />
       
    </head>
    <body style="<%= @body_style %>">
	      <header class='header'>
	      <div class='wrapper group'>
	        <a href='/' class='brand'>SOKO</a>
	        <nav class='menu'>
	          <a href='/blog/'>Blog</a>
	          <a href='/tour/'>Tour</a>
	          <a href='http://twitter.com/sokoebs' class='signin'>Twitter</a>
	        </nav>
	      </div>
	    </header>
		<main class="main">
             <%= render @view_module, @view_template, assigns %>
		</main>


			 <script src='/js/app.js'></script>
    </body>
</html>

web/templates/layout/login_bar.html.eex
<%= if @current_user do %>
  <li>
    <%= link "Logout", to: auth_path(@conn, :logout), method: :delete, class: "btn btn-danger" %>
  </li>
  <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
    <li>
      <%= link "Connect", to: auth_path(@conn, :login, "identity"), class: "btn btn-default"%>
    </li>
  <% end %>
<% else %>
  <li>
    <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
      <%= link "Login", to: auth_path(@conn, :login, "identity"), class: "btn btn-primary"%>
    <% end %>
  </li>
<% end %>

web/templates/layout/navigation.html.eex
<ul class='nav nav-tabs'>
  <li role='presentation' class='<%= active_on_current(@conn, private_page_path(@conn, :index)) %>'>
    <%= link "Private", to: private_page_path(@conn, :index) %>
  </li>
  <li role='presentation' class='<%= active_on_current(@conn, authorization_path(@conn, :index)) %>'>
    <%= link "Authorizations", to: authorization_path(@conn, :index) %>
  </li>
  <li role='presentation' class='<%= active_on_current(@conn, token_path(@conn, :index)) %>'>
    <%= link "Tokens", to: token_path(@conn, :index) %>
  </li>
</ul>

web/templates/layout/react.html.eex
<!DOCTYPE html>
<html>
<head>
    <title>Soko :: Spark Your Business</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/application.css">
     <link rel="stylesheet" href="/css/app.css">

</head>
<body >

<main id="main_container" role="main"></main>
    <footer id="main_footer">
      <small >

        Crafted with ♥ In Kampala By  <a href="http://sparkpl.ug/">Sparkplug</a>
       </small>
    </footer>

     <script src="<%= static_path(@conn, "/js/bundle.js") %>"></script>


</body>
</html>